### ISSUE TITLE
3.12 Compatability Issue

### ISSUE THREAD

**Issue by Gieberzo** [cisco-en-programmability/dnacentersdk#173]
This code relies on the "imp" module which is deprecated in 3.12 as seen here. https://discuss.python.org/t/how-do-i-migrate-from-imp/27885

See below for traceback when trying to run the module on 3.12

Traceback (most recent call last):
  File "C:\Users\MGIEPERT\OneDrive - azureford\Documents\programming\catc\catc_demo.py", line 1, in <module>
    from dnacentersdk import api
  File "C:\Users\MGIEPERT\AppData\Local\Programs\Python\Python312\Lib\site-packages\dnacentersdk\__init__.py", line 30, in <module>
    from .api import DNACenterAPI
  File "C:\Users\MGIEPERT\AppData\Local\Programs\Python\Python312\Lib\site-packages\dnacentersdk\api\__init__.py", line 39, in <module>
    from dnacentersdk.restsession import RestSession
  File "C:\Users\MGIEPERT\AppData\Local\Programs\Python\Python312\Lib\site-packages\dnacentersdk\restsession.py", line 27, in <module>
    from future import standard_library
  File "C:\Users\MGIEPERT\AppData\Local\Programs\Python\Python312\Lib\site-packages\future\standard_library\__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

**Comment by JosePabloOcampo1212** [comment]
The replacement was carried out
