### ISSUE TITLE
Issue with Ver 2.2.0

### ISSUE THREAD

**Issue by kiskander** [cisco-en-programmability/dnacentersdk#31]
After successfully installing , when importing this errors out (on Mac and Windows)

```
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dnacentersdk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rceara/venv/lib/python3.8/site-packages/dnacentersdk/__init__.py", line 36, in <module>
    from .api import DNACenterAPI
  File "/home/rceara/venv/lib/python3.8/site-packages/dnacentersdk/api/__init__.py", line 313, in <module>
    from .v2_2_1.event_management import \
  File "/home/rceara/venv/lib/python3.8/site-packages/dnacentersdk/api/v2_2_1/event_management.py", line 46, in <module>
    class EventManagement(object):
  File "/home/rceara/venv/lib/python3.8/site-packages/dnacentersdk/api/v2_2_1/event_management.py", line 544, in EventManagement
    is_parent_only=false,
NameError: name 'false' is not defined
>>> 
```

**Comment by jbogarin** [comment]
Kareem,

Done. Sorry for the delay. The problem was because of new APIs for version 2.2.1 that define a default value of true and false and we are using that to generate the code, but, obviously python needs True and False. 

I already uploaded version 2.2.1 to pypi.
